### ISSUE TITLE
Remove Critical Apps from Delete Page

### ISSUE THREAD

**Issue by Barrow1990** [sudobox-io/sb-install#13]
Take off the critical apps from been on the option to be deleted

Obviously unable to prevent these apps from been deleted via docker commands or via portainer but at least this eliminates any accidental deletes

<img width="377" alt="Critical Apps" src="https://user-images.githubusercontent.com/42769333/158084514-82d81e99-e3f5-448d-9fe1-c7bf7bb5701d.png">

**Comment by Xarritomi** [comment]
Critical apps have now been removed from the menu. The user also has the option to show these apps if they wish. Will be available in version 0.2.0 of sb-cli
