### ISSUE TITLE
Install new apps undefined

### ISSUE THREAD

**Issue by gadgethome** [sudobox-io/sb-install#4]
When you try to install new apps, the following error occur

│ CLI Version             │ SB-API Status           │
├─────────────────────────┼─────────────────────────┤
│ 1.0.0                   │ OK ✅                    │
└─────────────────────────┴─────────────────────────┘

radarr: undefined
undefined

1 apps queued - 0 Successfully Installed

? Would you like to install more Apps? (Y/n)

**Comment by Xarritomi** [comment]
Would you mind sending me the logs from `docker logs -f sb-backend`

**Comment by gadgethome** [comment]
sudo docker logs -f sb-backend
Fri, 11 Mar 2022 09:48:13 GMT morgan deprecated undefined format: specify a format at server.js:33:9
Fri, 11 Mar 2022 09:48:13 GMT morgan deprecated default format: use combined format at server.js:33:9
Now listening on PORT: 5830
Successfully connected to DB
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:52:18 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:52:19 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:52:19 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:56:21 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:56:22 GMT] "GET /apps HTTP/1.1" 200 25942 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:56:45 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:56:45 GMT] "GET /apps HTTP/1.1" 200 25942 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:57:31 GMT] "POST /apps/action HTTP/1.1" 200 133 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:57:43 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:57:56 GMT] "GET /apps HTTP/1.1" 200 26068 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:22 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:24 GMT] "GET /apps HTTP/1.1" 200 26074 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:36 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:39 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:39 GMT] "GET /apps HTTP/1.1" 200 26074 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:48 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:48 GMT] "GET /apps HTTP/1.1" 200 26074 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:54 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
TypeError: tempService.ports[0].split is not a function
    at /app/routes/apps.js:56:78
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:55 GMT] "POST /apps HTTP/1.1" 200 86 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:58:55 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:06 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:06 GMT] "GET /apps HTTP/1.1" 200 26069 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:10 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:10 GMT] "GET /apps HTTP/1.1" 200 26069 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:16 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
TypeError: tempService.ports[0].split is not a function
    at /app/routes/apps.js:56:78
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:16 GMT] "POST /apps HTTP/1.1" 200 86 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:16 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 09:59:36 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:07:49 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:07:59 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:08:01 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:08:03 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:08:04 GMT] "GET /apps HTTP/1.1" 200 26071 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:08:31 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:09:10 GMT] "GET /apps HTTP/1.1" 200 26077 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:09:57 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:15:00 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:15:02 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:21:51 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:02 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:03 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:06 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:06 GMT] "GET /apps HTTP/1.1" 200 26070 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:15 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:16 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:16 GMT] "GET /apps HTTP/1.1" 200 26070 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:24 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:24 GMT] "GET /apps HTTP/1.1" 200 26070 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:40 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
TypeError: tempService.ports[0].split is not a function
    at /app/routes/apps.js:56:78
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:40 GMT] "POST /apps HTTP/1.1" 200 86 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:22:40 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:24:54 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:24:58 GMT] "POST /status HTTP/1.1" 200 18 "-" "axios/0.24.0"
::ffff:172.19.0.8 - - [Fri, 11 Mar 2022 10:24:58 GMT] "GET /apps HTTP/1.1" 200 26071 "-" "axios/0.24.0"

**Comment by Xarritomi** [comment]
Thank you. So I think you are running the old version of sb-backend. Did you do a fresh installation?

**Comment by gadgethome** [comment]
I re-ran 

sudo curl -fsSl https://raw.githubusercontent.com/sudobox-io/sb-install/master/install.sh | sudo bash && source ~/.bashrc && sb

--------------- Sudobox Installer ---------------
  Pre Installer for SudoBox.io
  Version 0.0.1
  All documentation can be found at https://docs.sudobox.io

  Tasks :
     - Create SudoBox installation directories at /opt/sudobox
     - Install Docker & Docker-Compose
     - Create Docker Networks: sudobox & sudobox_private
     - Install the SudoBox CLI, Backend & Database Containers

     This script will run automatically in 10 seconds. Please exit if you wish to abort!


Proceeding with the Pre Installation...
Created SudoBox Directories
Installing and ensuring your system is upto date
Proceeding with installation dependencies...
Docker Installed, Skipping...
Docker-Compose installed, Skipping...
Docker Network ( sudobox )Exists, Skipping...
Created SudoBox backend compose file
sb-database is up-to-date
sb-backend is up-to-date
Created SudoBox backend Container


Finished installing all Dependencies, Moving to CLI Questions...
You can run SudoBox CLI at anytime using 'sb' or 'sudobox'

docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by cbennetto** [comment]
> I re-ran
> 
> sudo curl -fsSl https://raw.githubusercontent.com/sudobox-io/sb-install/master/install.sh | sudo bash && source ~/.bashrc && sb
> 
> --------------- Sudobox Installer --------------- Pre Installer for SudoBox.io Version 0.0.1 All documentation can be found at https://docs.sudobox.io
> 
> Tasks : - Create SudoBox installation directories at /opt/sudobox - Install Docker & Docker-Compose - Create Docker Networks: sudobox & sudobox_private - Install the SudoBox CLI, Backend & Database Containers
> 
> ```
>  This script will run automatically in 10 seconds. Please exit if you wish to abort!
> ```
> 
> Proceeding with the Pre Installation... Created SudoBox Directories Installing and ensuring your system is upto date Proceeding with installation dependencies... Docker Installed, Skipping... Docker-Compose installed, Skipping... Docker Network ( sudobox )Exists, Skipping... Created SudoBox backend compose file sb-database is up-to-date sb-backend is up-to-date Created SudoBox backend Container
> 
> Finished installing all Dependencies, Moving to CLI Questions... You can run SudoBox CLI at anytime using 'sb' or 'sudobox'
> 
> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied. See 'docker run --help'. docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied. See 'docker run --help'. docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied. See 'docker run --help'. docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=sb-cli": dial unix /var/run/docker.sock: connect: permission denied. See 'docker run --help'.

I had the same problem but got past it by using 'sudo su' and then running the install command.

**Comment by gadgethome** [comment]
I tried sudo su and then the command and get this error:

Created SudoBox Directories
Installing and ensuring your system is upto date
Proceeding with installation dependencies...
Docker Installed, Skipping...
Docker-Compose installed, Skipping...
Docker Network ( sudobox )Exists, Skipping...
Created SudoBox backend compose file
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml



Finished installing all Dependencies, Moving to CLI Questions...
You can run SudoBox CLI at anytime using 'sb' or 'sudobox'

**Comment by Xarritomi** [comment]
So, we have now pushed a new version of the sb-installer script. This should fix some of the issues you were having with permissions. 

In addition, please run the following command to update your sb containers.
`docker pull ghcr.io/sudobox-io/sb-backend && docker pull ghcr.io/sudobox-io/sb-cli && docker pull ghcr.io/sudobox-io/sb-companion`
