### ISSUE TITLE
Obfuscate any passwords that are typed in

### ISSUE THREAD

**Issue by HawksRepos** [sudobox-io/sb-install#7]
Hide any passwords as you type them in to the CLI/settings

![image](https://user-images.githubusercontent.com/24587652/158067336-39ddca8c-f3a2-4a68-87ac-6dacea9b6092.png)

**Comment by saltydk** [comment]
shouldn't this be in the cli repo?

**Comment by HawksRepos** [comment]
Easier to track the issues if they are all in one repo. Plus, users may not know where to post issues if they have to find the relevant repo's.

**Comment by Xarritomi** [comment]
This has now been implemented. Will be available in version 0.2.0 of sb-cli
